name: Transform tokens send from figma

on:
  repository_dispatch:
    types: update-tokens

defaults:
  run:
    shell: bash
    working-directory: packages/design-tokens

jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.file }}
          json: ${{ github.event.client_payload.tokens }}
          dir: ${{ github.event.client_payload.dir }}
      - name: Set Node.js 
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install yarn dependencies
        run: 'yarn install'
      - name: Transform design tokens 
        run: 'yarn build'
      - name: Format tokens
        run: 'yarn format'
        working-directory: './'
      # We now create a pull request 
      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ github.event.client_payload.commit_message }}
          title: ${{ github.event.client_payload.commit_title }}
          body: ${{ github.event.client_payload.commit_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'