# Name of the action visible in the action overview
name: Transform tokens send from figma
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: update-tokens

defaults:
  run:
    shell: bash
    working-directory: packages/design-tokens

# the following defines the jon that is run if the above is true
jobs:
  build:
    # the name for the entire job
    name: Transform Figma design tokens for specific platforms
    # we run this on ubuntu, leave this alone, if you don't have a good reason to change it
    runs-on: ubuntu-latest
    steps:
      # this lets us work in the actual repository 
      - uses: actions/checkout@main
      # this creates a json file from the stringified json from the request body
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          # it uses the name from your settings that was send as then tokenFileName parameter
          name: ${{ github.event.client_payload.file }}
          # it uses the json string that was send as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          # it uses the directory named "tokens" to store this json file (change this if you changed it above to use a different folder)
          dir: ${{ github.event.client_payload.dir }}
      # we now initialize node to run amazon style dictionary to compile the tokens
      - name: Set Node.js 
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install yarn dependencies
        run: 'yarn install'
      - name: Transform design tokens 
        run: 'yarn build'
      - name: Format tokens
        run: 'yarn format'
        working-directory: './'
      # We now create a pull request 
      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Tokens updated"
          title: "Design tokens updated"
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this parameter is optional and defaults to master but I am using main
          BRANCH_NAME: 'main'